### ISSUE TITLE
facts plugin fails on puppet 6

### ISSUE THREAD

**Issue by vchepkov** [choria-io/mcorpc-ruby-support#22]
```
# rpm -qa|egrep 'choria|puppet'
puppet-agent-6.1.0-1.el7.x86_64
puppetdb-termini-6.1.0-1.el7.noarch
puppetserver-6.1.0-1.el7.noarch
puppetdb-6.1.0-1.el7.noarch
puppet6-release-6.0.0-1.el7.noarch
choria-0.9.0-1.el7.x86_64

[root@master ~]# puppet module list|grep choria
├── choria-choria (v0.12.0)
├── choria-mcollective (v0.9.0)
├── choria-mcollective_agent_filemgr (v2.0.1)
├── choria-mcollective_agent_package (v5.1.0)
├── choria-mcollective_agent_puppet (v2.3.1)
├── choria-mcollective_agent_service (v4.0.1)
├── choria-mcollective_agent_shell (v1.0.3)
├── choria-mcollective_choria (v0.12.1)
├── choria-mcollective_util_actionpolicy (v3.0.0)

[vagrant@master ~]$ mco facts selinux -v
Discovering hosts using the mc method for 2 second(s) .... 1
Report for fact: selinux


The facts application failed to run: undefined method `length' for true:TrueClass

undefined method `length' for true:TrueClass (NoMethodError)
	from /opt/puppetlabs/puppet/lib/ruby/gems/2.5.0/gems/choria-mcorpc-support-2.20.4/lib/mcollective/util.rb:541:in `each'  <----
	from /opt/puppetlabs/puppet/lib/ruby/gems/2.5.0/gems/choria-mcorpc-support-2.20.4/lib/mcollective/util.rb:541:in `max_by'
	from /opt/puppetlabs/puppet/lib/ruby/gems/2.5.0/gems/choria-mcorpc-support-2.20.4/lib/mcollective/util.rb:541:in `field_size'
	from /opt/puppetlabs/puppet/lib/ruby/gems/2.5.0/gems/choria-mcorpc-support-2.20.4/lib/mcollective/application/facts.rb:15:in `show_single_fact_report'
	from /opt/puppetlabs/puppet/lib/ruby/gems/2.5.0/gems/choria-mcorpc-support-2.20.4/lib/mcollective/application/facts.rb:55:in `main'
	from /opt/puppetlabs/puppet/lib/ruby/gems/2.5.0/gems/choria-mcorpc-support-2.20.4/lib/mcollective/application.rb:283:in `run'
	from /opt/puppetlabs/puppet/lib/ruby/gems/2.5.0/gems/choria-mcorpc-support-2.20.4/lib/mcollective/applications.rb:23:in `run'
	from /opt/puppetlabs/puppet/lib/ruby/gems/2.5.0/gems/choria-mcorpc-support-2.20.4/bin/mco:33:in `<top (required)>'
	from /usr/bin/mco:23:in `load'
	from /usr/bin/mco:23:in `<main>'

```

**Comment by ripienaar** [comment]
ah, mco predates times when all facts werent strings :) will make a plan thanks

**Comment by ripienaar** [comment]
Ah no this is something else entirely not what I thought it is...and I don't see how this is happening.

Do you mind showing the output of:

```
mco rpc rpcutil get_fact fact=selinux -j -I <some affected node>
```

making sure that if you did `mco facts selinux -I <some affected node>` you'd get the same error

**Comment by vchepkov** [comment]
I think your hunch is true though, since it affects Integers as well:
```
[vagrant@master ~]$ mco facts processorcount
Report for fact: processorcount


The facts application failed to run, use -v for full error backtrace details: undefined method `length' for 2:Integer
```

Here is rpc run:

```
[vagrant@master ~]$ mco rpc rpcutil get_fact fact=selinux -j -I master.localdomain
[
  {
    "agent": "rpcutil",
    "action": "get_fact",
    "sender": "master.localdomain",
    "statuscode": 0,
    "statusmsg": "OK",
    "data": {
      "fact": "selinux",
      "value": true
    }
  }
]

```

**Comment by ripienaar** [comment]
Ah no, I see now this is indeed what I first though - though unclear why I cannot reproduce this.

https://github.com/choria-io/mcorpc-ruby-support/blob/424dbff77b2dc8b64780e5681012f307cffb5b6e/lib/mcollective/application/facts.rb#L42-L44

change these from `facts[value]` to `facts[value.inspect]` please and see if that sorts it out

**Comment by vchepkov** [comment]
That indeed fixed the problem. 

```
[vagrant@master ~]$ mco facts processorcount -j
Report for fact: processorcount

        2                                        found 1 times
[vagrant@master ~]$ mco facts selinux -j
Report for fact: selinux

        true                                     found 1 times
```

Can't connect to the node though, not sure what's wrong, observe this in choria.log 

```
{"component":"server","identity":"node.localdomain","level":"error","msg":"Message 93d3ea3f34f85cfc97b84a6e61b4345e from choria=node.localdomain@node.localdomain for agent discovery created at 2019-01-02 10:45:23 +0000 UTC is too old, TTL is 60","time":"2019-01-02T12:29:33Z"}

```

**Comment by ripienaar** [comment]
OK, we'll take on this fix thanks - the last bit is your clocks not being in sync, thanks @vchepkov

**Comment by vchepkov** [comment]
Silly me, I guess ntp module doesn't work

**Comment by vchepkov** [comment]
Something is still not quite right. Both VMs have selinux enabled and individually reported properly, but summary is wrong:

```
[vagrant@master ~]$ mco facts selinux -I master.localdomain
Report for fact: selinux

        true                                     found 1 times

Finished processing 1 / 1 hosts in 10.19 ms

[vagrant@master ~]$ mco facts selinux -I node.localdomain
Report for fact: selinux

        true                                     found 1 times

Finished processing 1 / 1 hosts in 9.83 ms

[vagrant@master ~]$ mco facts selinux 
Report for fact: selinux

        true                                     found 1 times

Finished processing 2 / 2 hosts in 8.51 ms
```

Noticed found 1 times?

**Comment by ripienaar** [comment]
hmm, are you sure both nodes have this fact? `mco rpc rpcutil get_fact fact=selinux`

**Comment by vchepkov** [comment]
```
[vagrant@master ~]$ mco rpc rpcutil get_fact fact=selinux -j
[
  {
    "agent": "rpcutil",
    "action": "get_fact",
    "sender": "master.localdomain",
    "statuscode": 0,
    "statusmsg": "OK",
    "data": {
      "fact": "selinux",
      "value": true
    }
  },
  {
    "agent": "rpcutil",
    "action": "get_fact",
    "sender": "node.localdomain",
    "statuscode": 0,
    "statusmsg": "OK",
    "data": {
      "fact": "selinux",
      "value": true
    }
  }
]

```

**Comment by vchepkov** [comment]
```
$ mco rpc rpcutil get_fact fact=selinux 
Discovering hosts using the mc method for 2 second(s) .... 2

 * [ ============================================================> ] 2 / 2


master.localdomain                       
    Fact: selinux
   Value: true

node.localdomain                         
    Fact: selinux
   Value: true


Summary of Value:

   true = 2


Finished processing 2 / 2 hosts in 11.01 ms

```

**Comment by ripienaar** [comment]
yeah I see you showed this before even, ok - i managed to reproduce the intial problem but this one not sure.

So lets try some things:

https://github.com/choria-io/mcorpc-ruby-support/blob/424dbff77b2dc8b64780e5681012f307cffb5b6e/lib/mcollective/application/facts.rb#L37

below that line add `pp resp`

and on https://github.com/choria-io/mcorpc-ruby-support/blob/424dbff77b2dc8b64780e5681012f307cffb5b6e/lib/mcollective/application/facts.rb#L51 add `pp facts`

**Comment by vchepkov** [comment]
```
[vagrant@master ~]$ mco facts selinux 
{:senderid=>"master.localdomain",
 :requestid=>"9e24d8528dd95632a215cb280b02dfed",
 :senderagent=>"rpcutil",
 :msgtime=>1546433565,
 :body=>
  {"statuscode"=>0,
   "statusmsg"=>"OK",
   "data"=>{:fact=>"selinux", :value=>true}}}
{"true"=>["master.localdomain"]}
{:senderid=>"node.localdomain",
 :requestid=>"9e24d8528dd95632a215cb280b02dfed",
 :senderagent=>"rpcutil",
 :msgtime=>1546433565,
 :body=>
  {"statuscode"=>0,
   "statusmsg"=>"OK",
   "data"=>{:fact=>"selinux", :value=>true}}}
{"true"=>["node.localdomain"]}
Report for fact: selinux

        true                                     found 1 times

Finished processing 2 / 2 hosts in 11.13 ms

```

**Comment by ripienaar** [comment]
so there were a few more of these bugs lurking and it would also have silently ignored nil values and false values.

https://gist.github.com/ripienaar/b4bd19ce14a6eac7511bcdabadc1a105

fixes all

**Comment by vchepkov** [comment]
@ripienaar , when do you think this fix can be included in a release?
thank you.

**Comment by ripienaar** [comment]
aiming to do releases this weekend, did the gist facts.rb resolve it for you?

**Comment by vchepkov** [comment]
yes, it did, thank you

**Comment by ripienaar** [comment]
thanks for confirming, releases soon
