### ISSUE TITLE
`mco plugin doc` fails when using choria_server

### ISSUE THREAD

**Issue by ExalDraen** [choria-io/mcorpc-ruby-support#26]
## Description
I think I've come across a bug / current limitation when using `choria server` rather than the old `mcollectived` which means that the `plugin doc` commands do not work.

I believe this is because they look for the metadata (DDL file) in the wrong place. They should look in the `choria-mcorpc-support` gem directory but they look in the configdir (set to `/etc/puppetlabs/mcollective`) and then fall back to `/etc/mcollective` which also doesn't contain the data.

Details of my setup are below.

```
[alexander.hermes@csqmgmt-puppetmaster01 mcollective]$ mco plugin doc agent/service -v

The plugin application failed to run: No such file or directory @ rb_sysopen - /etc/mcollective/rpc-help.erb

No such file or directory @ rb_sysopen - /etc/mcollective/rpc-help.erb (Errno::ENOENT)
	from /opt/puppetlabs/puppet/lib/ruby/gems/2.5.0/gems/choria-mcorpc-support-2.20.5/lib/mcollective/ddl/base.rb:46:in `read'  <----
	from /opt/puppetlabs/puppet/lib/ruby/gems/2.5.0/gems/choria-mcorpc-support-2.20.5/lib/mcollective/ddl/base.rb:46:in `help'
	from /opt/puppetlabs/puppet/lib/ruby/gems/2.5.0/gems/choria-mcorpc-support-2.20.5/lib/mcollective/application/plugin.rb:252:in `doc_command'
	from /opt/puppetlabs/puppet/lib/ruby/gems/2.5.0/gems/choria-mcorpc-support-2.20.5/lib/mcollective/application/plugin.rb:363:in `main'
	from /opt/puppetlabs/puppet/lib/ruby/gems/2.5.0/gems/choria-mcorpc-support-2.20.5/lib/mcollective/application.rb:283:in `run'
	from /opt/puppetlabs/puppet/lib/ruby/gems/2.5.0/gems/choria-mcorpc-support-2.20.5/lib/mcollective/applications.rb:23:in `run'
	from /opt/puppetlabs/puppet/lib/ruby/gems/2.5.0/gems/choria-mcorpc-support-2.20.5/bin/mco:33:in `<top (required)>'
	from /usr/bin/mco:23:in `load'
	from /usr/bin/mco:23:in `<main>'
```

NB the reason I think the config dir set to what I think it is is this log line:
```
I, [2019-03-14T09:49:46.198084 #16406]  INFO -- : config.rb:164:in `loadconfig' The Marionette Collective version 2.20.5 started by /usr/bin/choria_mcollective_agent_compat.rb using config file /etc/puppetlabs/mcollective/choria-shim.cfg
```

## Setup
In brief:
* Using choria_server instead of `mcollectived`
* Using manual config instead of SRV records (I dont' think that matters here but putting it here just in case)
```
# Choria server settings
# Ensure we use the new choria server instead of mcollectived
choria::server: true
mcollective::service_ensure: stopped
mcollective::service_enable: false

# We configure choria server and the mcollective plugin to use manual
# config since our SRV records point at prod
mcollective_choria::config:
  security.serializer: "json"
  use_srv_records: false
  puppetserver_host: "csqmgmt-puppetmaster01.grass.corp"
  puppetserver_port: 8140
  puppetca_host: "csqmgmt-puppetmaster01.grass.corp"
  puppetca_port: 8140
  puppetdb_host: "csqmgmt-puppetmaster01.grass.corp"
  puppetdb_port: 8081
  discovery_host: "csqmgmt-puppetmaster01.grass.corp"
  discovery_port: 8085
  middleware_hosts: "csqmgmt-puppetmaster01.grass.corp:4222"

choria::server_config:
  classesfile: "/opt/puppetlabs/puppet/cache/state/classes.txt"
  rpcaudit: 1
  plugin.rpcaudit.logfile: "/var/log/choria-audit.log"
  plugin.yaml: "/etc/puppetlabs/mcollective/generated-facts.yaml"
  plugin.choria.agent_provider.mcorpc.agent_shim: "/usr/bin/choria_mcollective_agent_compat.rb"
  plugin.choria.agent_provider.mcorpc.config: "/etc/puppetlabs/mcollective/choria-shim.cfg"
  plugin.choria.agent_provider.mcorpc.libdir: "/opt/puppetlabs/mcollective/plugins"
  plugin.choria.puppetserver_host: "csqmgmt-puppetmaster01.grass.corp"
  plugin.choria.puppetserver_port: 8140
  plugin.choria.puppetca_host: "csqmgmt-puppetmaster01.grass.corp"
  plugin.choria.puppetca_port: 8140
  plugin.choria.puppetdb_host: "csqmgmt-puppetmaster01.grass.corp"
  plugin.choria.puppetdb_port: 8081
  plugin.choria.discovery_host: "csqmgmt-puppetmaster01.grass.corp"
  plugin.choria.discovery_port: 8085
  plugin.choria.middleware_hosts: "csqmgmt-puppetmaster01.grass.corp:4222"

# MCO/Choria client settings
mcollective::client: true

# Use new-style audit logging to log requests
mcollective::server_config:
  rpcauditprovider: "choria"
  plugin.rpcaudit.logfile: "/var/log/puppetlabs/choria-audit.log"
```

**Comment by smortex** [comment]
Closing as this feature was added to choria in choria-io/go-choria#1223 and the current mcorpc-ruby-support now rely on choria so `mco plugin doc agent/package` is equivalent to `choria plugin doc agent/package` and present the documentation that was previously broken.
