### ISSUE TITLE
Array validation fails

### ISSUE THREAD

**Issue by jay7x** [choria-io/mcorpc-ruby-support#58]
I have mco agent which take array on input. But this input fails validation somehow.

Here is DDL of action related:
```
action 'exporter', :description => 'Returns Prometheus exporter metrics requested' do
  display :always

  input :url,
        :prompt => 'URL',
        :description => 'Prometheus exporter URL to query',
        :type => :string,
        :validation => '.*',
        :maxlength => 64 * 1024,
        :optional => false

  input :metrics,
        :prompt => 'Metrics',
        :description => 'Metrics to return from URL',
        :type => :array,
        :default => [],
        :optional => true

  output :metrics,
         :description => 'Metrics returned',
         :display_as => 'Metrics',
         :type => :hash,
         :default => {}
end
```

Script to debug:
```
#!/opt/puppetlabs/puppet/bin/ruby

require "mcollective"
include MCollective::RPC

c = rpcclient("query")
printrpc(c.exporter(:url => "http://127.0.0.1:9070", :metrics => ['namenode_state']))
```

Script output:
```
Traceback (most recent call last):
        7: from ./query.exporter.rb:9:in `<main>'
        6: from /opt/puppetlabs/puppet/lib/ruby/gems/2.5.0/gems/choria-mcorpc-support-2.20.8/lib/mcollective/rpc/client.rb:250:in `method_missing'
        5: from /opt/puppetlabs/puppet/lib/ruby/gems/2.5.0/gems/choria-mcorpc-support-2.20.8/lib/mcollective/rpc/client.rb:179:in `validate_request'
        4: from /opt/puppetlabs/puppet/lib/ruby/gems/2.5.0/gems/choria-mcorpc-support-2.20.8/lib/mcollective/ddl/agentddl.rb:233:in `validate_rpc_request'
        3: from /opt/puppetlabs/puppet/lib/ruby/gems/2.5.0/gems/choria-mcorpc-support-2.20.8/lib/mcollective/ddl/agentddl.rb:233:in `each_key'
        2: from /opt/puppetlabs/puppet/lib/ruby/gems/2.5.0/gems/choria-mcorpc-support-2.20.8/lib/mcollective/ddl/agentddl.rb:241:in `block in validate_rpc_request'
        1: from /opt/puppetlabs/puppet/lib/ruby/gems/2.5.0/gems/choria-mcorpc-support-2.20.8/lib/mcollective/ddl/base.rb:132:in `validate_input_argument'
/opt/puppetlabs/puppet/lib/ruby/gems/2.5.0/gems/choria-mcorpc-support-2.20.8/lib/mcollective/ddl/base.rb:152:in `rescue in validate_input_argument': Cannot validate input metrics: wrong number of arguments (given 1, expected 2) (MCollective::DDLValidationError)
```

**Comment by ripienaar** [comment]
@jay7x wanna check if this patch would fix it for you?

**Comment by jay7x** [comment]
Thanks! It seems validation succeed this time!
