### ISSUE TITLE
Hash validation fails

### ISSUE THREAD

**Issue by jay7x** [choria-io/mcorpc-ruby-support#60]
I have mco agent which take hash on input. But this input fails validation somehow.

Here is DDL of action related:
```
action 'rest', :description => 'Returns REST API reply' do
  display :always

  input :url,
        :prompt => 'URL',
        :description => 'API URL to query',
        :type => :string,
        :validation => '.*',
        :maxlength => 10 * 1024,
        :optional => false

  input :method,
        :prompt => 'Method',
        :description => 'HTTP method to use',
        :type => :list,
        :list => ['GET','POST','PUT','DELETE','HEAD','LIST'],
        :default => 'GET',
        :optional => true

  input :headers,
        :prompt => 'Headers',
        :description => 'HTTP headers to send',
        :type => :hash,
        :default => {},
        :optional => true

  input :data,
        :prompt => 'Data',
        :description => 'HTTP data to send',
        :type => :string,
        :validation => '.*',
        :maxlength => 64 * 1024,
        :default => '',
        :optional => true

  output :code,
         :description => 'HTTP Status code',
         :display_as => 'Code',
         :type => :string,
         :default => ''

  output :message,
         :description => 'HTTP reply message',
         :display_as => 'Message',
         :type => :string,
         :default => ''

  output :body,
         :description => 'HTTP reply body',
         :display_as => 'Body',
         :type => :string,
         :default => ''

  output :headers,
         :description => 'HTTP reply headers',
         :display_as => 'Headers',
         :type => :hash,
         :default => {}
end
```

Script to debug:
```
#!/opt/puppetlabs/puppet/bin/ruby

require "mcollective"
include MCollective::RPC

c = rpcclient("query")
printrpc(
  c.rest(
    :url => "http://127.0.0.1:9070",
    :method => 'GET',
    :headers => {
      'X-Vault-Token' => 'abcdefghijklmn',
      'Content-Type' => 'application/json',
    },
    :data => 'foo'
  )
)
```

Script output:
```
Traceback (most recent call last):
        8: from ./query.rest.rb:8:in `<main>'
        7: from /opt/puppetlabs/puppet/lib/ruby/gems/2.5.0/gems/choria-mcorpc-support-2.20.8/lib/mcollective/rpc/client.rb:250:in `method_missing'
        6: from /opt/puppetlabs/puppet/lib/ruby/gems/2.5.0/gems/choria-mcorpc-support-2.20.8/lib/mcollective/rpc/client.rb:179:in `validate_request'
        5: from /opt/puppetlabs/puppet/lib/ruby/gems/2.5.0/gems/choria-mcorpc-support-2.20.8/lib/mcollective/ddl/agentddl.rb:233:in `validate_rpc_request'
        4: from /opt/puppetlabs/puppet/lib/ruby/gems/2.5.0/gems/choria-mcorpc-support-2.20.8/lib/mcollective/ddl/agentddl.rb:233:in `each_key'
        3: from /opt/puppetlabs/puppet/lib/ruby/gems/2.5.0/gems/choria-mcorpc-support-2.20.8/lib/mcollective/ddl/agentddl.rb:241:in `block in validate_rpc_request'
        2: from /opt/puppetlabs/puppet/lib/ruby/gems/2.5.0/gems/choria-mcorpc-support-2.20.8/lib/mcollective/ddl/base.rb:147:in `validate_input_argument'
        1: from /opt/puppetlabs/puppet/lib/ruby/gems/2.5.0/gems/choria-mcorpc-support-2.20.8/lib/mcollective/validator.rb:69:in `validate'
/opt/puppetlabs/puppet/lib/ruby/gems/2.5.0/gems/choria-mcorpc-support-2.20.8/lib/mcollective/validator.rb:69:in `hash': Cannot validate input headers: wrong number of arguments (given 1, expected 0) (MCollective::DDLValidationError)
```

**Comment by ripienaar** [comment]
OK v.similar to the other one, feel like sending a PR?

**Comment by jay7x** [comment]
If you asking about PR from me then no.. :( at least not today..
